version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql
    environment: 
      MYSQL_DATABASE: "devops"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - two-tier
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  flask:
    build:
      context: .
    container_name: two-tier-backend
    ports:
      - "5000:5000"

    environment: # These env vars are now used by wait-for-db.sh and your Flask app
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: devops
    networks:
      - two-tier
    depends_on:
      - mysql
    restart: always
   
volumes:
  mysql-data:

networks:
  two-tier:
