version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql
    environment: # Corrected from 'enviroments'
      MYSQL_DATABASE: "devops"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - two-tier

  flask:
    build:
      context: .
    container_name: two-tier-backend
    ports:
      - "5000:5000"
    environment: # Corrected from 'enviroments'
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: devops
    networks:
      - two-tier
    depends_on:
      - mysql

volumes:
  mysql-data:

networks:
  two-tier:
